### ISSUE TITLE
Playing embedded youtube videos on linux player

### ISSUE THREAD

**Issue by gitthismoney** [xibosignage/xibo-linux#114]
Hi all, 

When playing a layout with embedded youtube videos the linux player reports that it does not currently recognize any of the video formats available... supposedly due to lack of html5 video support? 

I attached a screenshot of the message + the console window which has another error message... 

let me know if i can try any thing or provide any further details, thank you!
![Screen Shot 2019-09-04 at 12 00 20 PM](https://user-images.githubusercontent.com/404807/64283182-c9dffb80-cf0b-11e9-854b-6b6835528b32.png)

Josh

**Comment by alexharrington** [comment]
I tested this with R3 on Ubuntu 18.04 using the method we suggest for embedding Youtube (via the API) and it worked as expected.

See https://xibo.org.uk/docs/setup/autoplay-embedded-youtube-videos
