### ISSUE TITLE
Error when Compliling using SPDLOG 1.4.0

### ISSUE THREAD

**Issue by joacom** [xibosignage/xibo-linux#115]
Hello, 
Dont know if this is relevant for you or not (if not just close the issue), but i have a compile error, and i did a change in the source to compile

This seems to get my compile going to next step: 
xibo-linux/player/xmlsink/XmlLoggerSink.hpp

replace 
`       message += "<message>" + fmt::to_string(msg.raw) + "</message>";`
with
`       message += "<message>" + fmt::to_string("msg.raw") + "</message>";`

Here is the error:

> [ 38%] Building CXX object player/CMakeFiles/player.dir/XiboApp.cpp.o
> In file included from /home/pi/build/XiboLinuxStack_1.8-r3/xibo-linux/player/Xib                                                                                                                                                             oApp.cpp:8:
> /home/pi/build/XiboLinuxStack_1.8-r3/xibo-linux/player/xmlsink/XmlLoggerSink.hpp                                                                                                                                                             : In member function ‘std::__cxx11::string XmlLoggerSink<Mutex>::formatMessage(c                                                                                                                                                             onst spdlog::details::log_msg&)’:
> /home/pi/build/XiboLinuxStack_1.8-r3/xibo-linux/player/xmlsink/XmlLoggerSink.hpp                                                                                                                                                             :48:53: error: ‘const struct spdlog::details::log_msg’ has no member named ‘raw’
>          message += "<message>" + fmt::to_string(msg.raw) + "</message>";
>                                                      ^~~
> player/CMakeFiles/player.dir/build.make:75: recipe for target 'player/CMakeFiles                                                                                                                                                             /player.dir/XiboApp.cpp.o' failed
> make[2]: *** [player/CMakeFiles/player.dir/XiboApp.cpp.o] Error 1
> CMakeFiles/Makefile2:106: recipe for target 'player/CMakeFiles/player.dir/all' f                                                                                                                                                             ailed
> make[1]: *** [player/CMakeFiles/player.dir/all] Error 2
> Makefile:140: recipe for target 'all' failed
> make: *** [all] Error 2
>

**Comment by Stivius** [comment]
@joacom it was checked only on 1.1.0. If you want to build from sources you'd better to use docker.
