### ISSUE TITLE
Video from TVHeadend

### ISSUE THREAD

**Issue by srekkas** [xibosignage/xibo-linux#122]
Hello

   Video wont play from network (TVHeadend server). Player is 1.8 R3
Throws errors:
Your GStreamer installation is missing a plug-in.
Internal data stream error.

Video can be mpeg or H246 (mpeg-4 avc (part10)).
Audio can be mpeg, ADTS, LATM.

**Comment by Stivius** [comment]
Hello @srekkas. Could you provide the video example so we can reproduce it locally?

**Comment by srekkas** [comment]
It is network stream, so not very accurate. Recorded with VLC.

https://transfer.xibo.org.uk/dfcfe8c9452c
https://transfer.xibo.org.uk/56735a791d90

**Comment by Stivius** [comment]
Needs to be checked in the upcoming R4 after #87.
