### ISSUE TITLE
xibo is crashing when it will play video in 4k

### ISSUE THREAD

**Issue by renancamargo** [xibosignage/xibo-linux#135]
Player Version: 1.8 R3
OS Version: tested on Ubuntu 18.04

Issue: xibo is crashing when it will play video in 4k

video: MPEG-4 | H.264, AAC |  2160 × 3840 
same video file works smoothly on xibo for windows

Error Message: (player:1993): Gtk-CRITICAL **: 10:32:38.053: gtk_widget_set_size_request: assertion 'width >= -1' failed

**Comment by dasgarner** [comment]
Thank you for your report - would you be able to try the version of the player in the `edge` channel to see if it has improved?

**Comment by renancamargo** [comment]
it's working. thanks!

**Comment by dasgarner** [comment]
thank you for confirming - pleased to hear it!
