### ISSUE TITLE
GStreamer gst_poll_read_control assert after long playback

### ISSUE THREAD

**Issue by PawelDefee** [xibosignage/xibo-linux#137]
### The bug

Xibo Linux player hangs after a long playback (8-20 hours). Black screen only is seen, the standard output log (set to TRACE) is permanently halted. Standard error output gets flooded with the following message at the rate of around 20 lines per second:

``
(player:3191):` GStreamer-CRITICAL **:12:12:51.609: gst_poll_read_control: assertion 'set != NULL' failed
``
### The setup

Xibo Linux player version latest/stable 1.8-R3 from Snap store is used. I have a simple FullHD layout with one full screen region and the following media assigned to it for playback:

* 8 JPEG images, 10 seconds duration for each
* 5 mp4 videos of the following durations: 13s, 9s, 29s, 20s, 115s

The total duration for the layout is 266s. It is scheduled to play in 'always' mode. The player hardware is a standard PC box and the operating system is Ubuntu 16.04.

### Troubleshooting

Looking for the particular assert on the net, everything points to file descriptors being leaked. Looking at total descriptors being open for the 'player' binary, I can see the following:

``
$ lsof -u user | grep player | wc -l
``
`1276`

I rebooted the system and started over. When looking at the list of open descriptors every 266 seconds, I can see that the number of descriptors of "type=STREAM" does not appear to increase (stays constant at 24) when checked at the time when the first media item in the sequence is being show:

``
$ lsof -u user | grep player | grep type=STREAM
``

However , the total count of all open descriptors for the player does appear to increase monotonically, however, not at a constant rate but at 1-7 per iteration of the layout. I arrived at this conclusion by monitoring the following command for a number of iterations:

``
$ lsof -u user | grep player |wc -l
``

### Likely related issues

The following issues are very likely related to this one:

https://github.com/xibosignage/xibo-linux/issues/121
https://community.xibo.org.uk/t/linux-player-error/20665

**Comment by Stivius** [comment]
Hi, thank you for such a detailed bug report! Needs to be checked in the upcoming R4 after #87.
