### ISSUE TITLE
Compilation on an ARM platform

### ISSUE THREAD

**Issue by Supermanu** [xibosignage/xibo-linux#142]
**Describe the bug**
Thanks a lot for this awesome software. Just to let you know, when compiling on an ARM platform (raspberry here), it fails while getting the [cpuid](https://github.com/xibosignage/xibo-linux/blob/d10d6a32fc3a9f83b7114969a38fd5a6a97a1cbc/player/common/system/HardwareKeyGenerator.cpp#L35), I guess it's related to the cpu platform. Otherwise it works like a charm.

**To Reproduce**
Compile on an ARM platform.

**Logs**
```
[ 94%] Building CXX object player/options/CMakeFiles/options.dir/HardwareKey.cpp.o
/home/xiboclient/compile/xibo-linux/player/options/HardwareKey.cpp: In static member function ‘static std::__cxx11::string HardwareKey::cpuid()’:
/home/xiboclient/compile/xibo-linux/player/options/HardwareKey.cpp:40:19: warning: ‘ecx’ is used uninitialized in this function [-Wuninitialized]
        : "memory");
                   ^
/home/xiboclient/compile/xibo-linux/player/options/HardwareKey.cpp:23:32: note: ‘ecx’ was declared here
     unsigned int eax = 0, ebx, ecx, edx;
                                ^~~
/home/xiboclient/compile/xibo-linux/player/options/HardwareKey.cpp:40:19: error: impossible constraint in ‘asm’
        : "memory");
                   ^
player/options/CMakeFiles/options.dir/build.make:75: recipe for target 'player/options/CMakeFiles/options.dir/HardwareKey.cpp.o' failed
make[2]: *** [player/options/CMakeFiles/options.dir/HardwareKey.cpp.o] Error 1
CMakeFiles/Makefile2:275: recipe for target 'player/options/CMakeFiles/options.dir/all' failed
make[1]: *** [player/options/CMakeFiles/options.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

**Environment (please complete the following information):**
- Linux Distro: Ubuntu
- Linux Desktop Environment: No desktop environment.
- How the player was launched: source code.
- Player Version: develop branch.

**Comment by dasgarner** [comment]
Thank you for your bug report - we don't have any plans to support ARM at this stage, although we may do in the future. Our focus is on getting a feature full and stable x86 version of this player working first. I will leave this issue open for informational purposes.

**Comment by Supermanu** [comment]
Sure, I was not expecting anything soon, especially as it is easy to work around. Thanks again!

**Comment by joacom** [comment]
@Supermanu  did you comment out the code or did you modify it? Could you please share? Thanks :)

**Comment by Supermanu** [comment]
I just commented the code and gave dummy values:
```
-    asm volatile("cpuid" : "=a"(*eax), "=b"(*ebx), "=c"(*ecx), "=d"(*edx) : "0"(*eax), "2"(*ecx) : "memory");
+    /*asm volatile("cpuid" : "=a"(*eax), "=b"(*ebx), "=c"(*ecx), "=d"(*edx) : "0"(*eax), "2"(*ecx) : "memory");*/
+    *eax = 1; *ebx = 2; *ecx = 3; *edx = 4;
```
Nothing fancy :P.

**Comment by joacom** [comment]
> I just commented the code and gave dummy values:
> 
> ```
> -    asm volatile("cpuid" : "=a"(*eax), "=b"(*ebx), "=c"(*ecx), "=d"(*edx) : "0"(*eax), "2"(*ecx) : "memory");
> +    /*asm volatile("cpuid" : "=a"(*eax), "=b"(*ebx), "=c"(*ecx), "=d"(*edx) : "0"(*eax), "2"(*ecx) : "memory");*/
> +    *eax = 1; *ebx = 2; *ecx = 3; *edx = 4;
> ```
> 
> Nothing fancy :P.

Thnx :) I will do it the same way!

**Comment by generic-beat-detector** [comment]
@Supermanu 

Which release/tag/commit? 

Thanks in advance.

**Comment by Supermanu** [comment]
It is applied on 69dc30b71c420c0c5bdadd92801f08cc5ed580b6. But it has been working since several months.

**Comment by generic-beat-detector** [comment]
@ Supermanu

Thank you. I applied the changes as you suggested __but__ built against  [64a0435](https://github.com/xibosignage/xibo-linux/commit/64a0435c59baa6af9dc9ba68080e0305a922a4ec) (1.8-r4); Build was successful. 

However, trying to launch `build/bin/player` reports:

    $ LD_LIBRARY_PATH=build/bin/libs:$LD_LIBRARY_PATH ./build/bin/player 

    Update CMS settings using player options app

I suspect this means "execute `build/bin/options`" first? But executing `options` fails with:

    $ LD_LIBRARY_PATH=build/bin/libs:$LD_LIBRARY_PATH ./build/bin/options 

    terminate called after throwing an instance of 'Glib::FileError'`

Have you ever run into such issues? I suspected Glib version incompatibilities, but the binary's Glib dependencies:

    $ readelf -d build/bin/options | grep libglib
     0x00000001 (NEEDED)                     Shared library: [libglibmm-2.4.so.1]
     0x00000001 (NEEDED)                     Shared library: [libglib-2.0.so.0]

and the system's Glib version seem to match 

    $ ldd build/bin/options | grep libglib
    	libglibmm-2.4.so.1 => /usr/lib/arm-linux-gnueabihf/libglibmm-2.4.so.1 (0x76908000)
    	libglib-2.0.so.0 => /usr/lib/arm-linux-gnueabihf/libglib-2.0.so.0 (0x76816000)

    $ ls /usr/lib/arm-linux-gnueabihf/libglib* -F
    /usr/lib/arm-linux-gnueabihf/libglib-2.0.so.0@
    /usr/lib/arm-linux-gnueabihf/libglib-2.0.so.0.5600.3
    /usr/lib/arm-linux-gnueabihf/libglibmm-2.4.so.1@
    /usr/lib/arm-linux-gnueabihf/libglibmm-2.4.so.1.3.0
    /usr/lib/arm-linux-gnueabihf/libglibmm_generate_extra_defs-2.4.so.1@
    /usr/lib/arm-linux-gnueabihf/libglibmm_generate_extra_defs-2.4.so.1.3.0

My system is Ubuntu Mate (32bit) on  RPi 3B:

    $ lsb_release -a  2>/dev/null
    Distributor ID:	Ubuntu
    Description:	Ubuntu 18.04.2 LTS
    Release:	18.04
    Codename:	bionic

    $ uname -m
    armv7l

**Comment by Supermanu** [comment]
You need to execute the binaries directly from the `bin` folder.

**Comment by generic-beat-detector** [comment]
@Supermanu 

Yup! How embarrassing! `build/bin/options` finally launched. Now let's see how it goes...

Best regards.

**Comment by Kotletta-TT** [comment]
I`m try make in raspbian(no desktop) last version. I install or build all lib dependence, i try your command `cmake -DCMAKE_BUILD_TYPE=Release -DSNAP_BUILD=OFF -H. -B_build` and try deffault `mkdir build && cd build && cmake ..`, but i getting an error `– The C compiler identification is GNU 7.4.0
– The CXX compiler identification is GNU 7.4.0
– Check for working C compiler: /usr/bin/cc
– Check for working C compiler: /usr/bin/cc – works
– Detecting C compiler ABI info
– Detecting C compiler ABI info - done
– Detecting C compile features
– Detecting C compile features - done
– Check for working CXX compiler: /usr/bin/c++
– Check for working CXX compiler: /usr/bin/c++ – works
– Detecting CXX compiler ABI info
– Detecting CXX compiler ABI info - done
– Detecting CXX compile features
– Detecting CXX compile features - done
– Found PkgConfig: /usr/bin/pkg-config (found version “0.29.1”)
– Looking for pthread.h
– Looking for pthread.h - found
– Performing Test CMAKE_HAVE_LIBC_PTHREAD
– Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
– Looking for pthread_create in pthreads
– Looking for pthread_create in pthreads - not found
– Looking for pthread_create in pthread
– Looking for pthread_create in pthread - found
– Found Threads: TRUE
– Found Boost: /usr/local/include (found suitable exact version “1.70.0”) found components: filesystem system date_time thread chrono atomic
– Checking for modules ‘gstreamer-pbutils-1.0;gstreamer-video-1.0>=1.14.0;gstreamer-plugins-base-1.0>=1.14.0’
– Found gstreamer-pbutils-1.0, version 1.14.5
– Found gstreamer-video-1.0, version 1.14.5
– Found gstreamer-plugins-base-1.0, version 1.14.5
– Checking for module ‘webkitgtk-3.0>=2.4.10’
– Found webkitgtk-3.0, version 2.4.11
– Checking for module ‘gtkmm-3.0>=3.22.0’
– Found gtkmm-3.0, version 3.22.2
– Checking for module ‘glibmm-2.4>=2.56.0’
– Found glibmm-2.4, version 2.56.0
– Checking for module ‘spdlog>=1.4.1’
– Found spdlog, version 1.4.2
– Found GTest: /usr/lib/libgtest.so
– Checking for module ‘libzmq>=4.3.0’
– Found libzmq, version 4.3.2
objdump: ‘a.out’: No such file
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GMOCK
linked by target “schedule_tests” in directory /home/liatoss/Downloads/Xibo/xibo-linux-develop/player/schedule/tests
linked by target “common_tests” in directory /home/liatoss/Downloads/Xibo/xibo-linux-develop/player/common/tests

– Configuring incomplete, errors occurred!
See also “/home/liatoss/Downloads/Xibo/xibo-linux-develop/CMakeFiles/CMakeOutput.log”.
See also “/home/liatoss/Downloads/Xibo/xibo-linux-develop/CMakeFiles/CMakeError.log”.
`
I small experience build C app. I search internet, but no solution.
