### ISSUE TITLE
GStreamer gst_poll_read_control assert error after long playback - CentOS 7

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo-linux#153]
**Describe the bug**
This bug is the same as described in XFL-92. After an extended period of playing videos and images in a Layout, the error is returned.

**To Reproduce**
Same steps as XFL-92 issue, set a Layout to display on the Player that contains videos and images. After a while the error will be returned. 

**Logs**
Error returned is:
(player:10573):` GStreamer-CRITICAL **:13:00:16.992: gst_poll_read_control: assertion 'set != NULL' failed
**Screenshots**
![image](https://user-images.githubusercontent.com/40995523/70325948-2fa19380-182b-11ea-9883-b354132839ca.png)

**Environment (please complete the following information):**
- Linux Disto: CentOS 7
- Linux Desktop Environment: KDE 4.14.8
- How the player was launched: snap
- Player Version: 1.8 R4

**Comment by cdcstl** [comment]
Describe the bug
Xibo-player bug, After an extended period of playing videos and images in a Layout, the error is returned.

To Reproduce
Xibo-player bug, After a while the error will be returned.

Logs
Error returned is:
gst_poll_read_control: assertion 'set != NULL' failed



Environment (please complete the following information):

    Linux Disto: CentOS 7
    Linux Desktop Environment: MATE
    How the player was launched: snap
    Player Version: 1.8 R4

and also on

    Linux Disto: Ubuntu 18.04 
    Linux Desktop Environment: Gnome
    How the player was launched: snap
    Player Version: 1.8 R4

**Comment by DanielBW1** [comment]
I have been running the same layout and media on R39 and so far I have not encountered this issue.

OS: centOS 7, KDE environment

**Comment by daviddumaison** [comment]
Why does it moved from Done to Priority for Edge ? Does some people still experiencing this issue ?

**Comment by daviddumaison** [comment]
Is someone still experiencing this issue ?

**Comment by dasgarner** [comment]
Yes some of our testers are experiencing it still

**Comment by birkenfeld** [comment]
I'm seeing it too, with a layout using videos, on CentOS 8.

**Comment by jet-c-21** [comment]
Which version of gstreamer produce this error? I am using 1.14 gstreamer on Jetson Nano and meet the same error
