### ISSUE TITLE
Error build in docker

### ISSUE THREAD

**Issue by Kotletta-TT** [xibosignage/xibo-linux#155]
**Describe the bug**
Instruction build docker - bad result.

**To Reproduce**
I step by step this instruction on my VM (Ubuntu Server 18.04 amd64), but i try start ./options i get Error:
`./options: error while loading shared libraries: libgtkmm-3.0.so.1: cannot open shared object file: No such file or directory` 

**Expected behavior**
Start options

**Environment (please complete the following information):**
- Linux Disto: [VM Ubuntu Server 18.04 amd64]
- Linux Desktop Environment: [openbox] 
- How the player was launched: [compiled binaries]
- Player Version: [1.8-R4]

I think this is wrong instruction, i added binary files(of docker container) but, i don`t set dependence on my system. Please correct this instruction: Added info about run app of docker-container or set dependence in root system. Thank you.

**Comment by Stivius** [comment]
Hello! Thank you for your report, however, we don't officially support running from raw binaries. You can build it on your own and add missing dependencies. Our main focus is snap package for now.
