### ISSUE TITLE
Debian decided to put gtk-sink in own apk package

### ISSUE THREAD

**Issue by joacom** [xibosignage/xibo-linux#156]
**Debian decided to add GTK-SINK as own package**

Just a heads up if ubuntu decides to do the same, I know you guys only develop and support Ubuntu officially  :)

GTK-sink is found in this package: apt-get install gstreamer1.0-gtk3

**Comment by Stivius** [comment]
As far as I know, it has already been added to a similar package since Ubuntu 18.04 (bionic). Anyway, thanks for letting us know!
