### ISSUE TITLE
Missing Plugin: Advanced Streaming Format (ASF) (video/x-ms-asf)

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo-linux#164]
OP: https://community.xibo.org.uk/t/plug-in-error-missing-decoder-in-linux-player-1-8r4/21547

Should we support this format?

**Comment by Stivius** [comment]
It's from `ugly` GStreamer plugins as stated from here: https://gstreamer.freedesktop.org/documentation/asf/index.html?gi-language=c

`GStreamer Ugly Plug-ins is a set of plug-ins that have good quality and correct functionality, but distributing them might pose problems. The license on either the plug-ins or the supporting libraries might not be how we'd like. The code might be widely known to present patent problems.`
Source: https://gstreamer.freedesktop.org/modules/gst-plugins-ugly.html

Do we need to include it? Actually, in concerns `bad` plugins as well.
https://gstreamer.freedesktop.org/modules/gst-plugins-bad.html

**Comment by dasgarner** [comment]
I don't think so - I will get back to the OP.
