### ISSUE TITLE
No suitable plugin

### ISSUE THREAD

**Issue by srekkas** [xibosignage/xibo-linux#189]
**Describe the bug**
After upgrade from 46 build (R5 candidate) to R5 video wont play. Black screen

**To Reproduce**
Upgrade to R5 and play video

**Expected behavior**
Video must play

**Logs**
logs screenshots

**Screenshots**
![image](https://user-images.githubusercontent.com/24478189/79745721-77741380-8311-11ea-900c-4fa4cc4c9f8a.png)

**Environment (please complete the following information):**
- Linux Disto: Ubuntu 18-04
- Linux Desktop Environment: Gnome
- How the player was launched: SNAP
- Player Version: 1.8-R5

**Comment by dasgarner** [comment]
Is this still a problem in the latest revision (r50)?
