### ISSUE TITLE
manuel installation, notfound library. 

### ISSUE THREAD

**Issue by serbasii** [xibosignage/xibo-linux#202]
**Describe the bug**
i try to build and install on _revert-138-master_ branch, the building works but installing failed.

** Terminal Logs**

revert-138-master/_build$ sudo make install
[ 24%] Built target common
[ 40%] Built target networking
[ 47%] Built target schedule
[ 85%] Built target player
[ 93%] Built target schedule_tests
[ 95%] Built target options
[ 98%] Built target common_tests
[100%] Built target watchdog
Install the project...
-- Install configuration: "Release"
-- Installing: /app/xibo-linux-revert-138-master/_build/bin/libs/
cp: failed to access 'hread_soname_path-NOTFOUND': No such file or directory

**cmake_install.cmake file logs**

.....

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  execute_process(COMMAND cp -lpthread_soname_path-NOTFOUND /app/xibo-linux-revert-138-master/_build/bin/libs/)
endif()

**Environment (please complete the following information):**
- Linux Disto: [Ubuntu 18.04 LTS]

**Comment by serbasii** [comment]
This is not a question, this is a bug.

Likewise, I have also tried 1.8-r4 tag, same result.

`cp: failed to access 'hread_soname_path-NOTFOUND': No such file or directory`

run under docker,

```
[100%] Linking CXX executable ../bin/player
[100%] Built target player
[ 24%] Built target common
[ 40%] Built target networking
[ 47%] Built target schedule
[ 85%] Built target player
[ 93%] Built target schedule_tests
[ 95%] Built target options
[ 98%] Built target common_tests
[100%] Built target watchdog
Install the project...
-- Install configuration: "Release"
-- Installing: /app/_build/bin/libs/
**cp: failed to access 'hread_soname_path-NOTFOUND': No such file or directory**
Removing intermediate container 254eea59246c
 ---> 6d26efdcde15
Step 33/33 : ENTRYPOINT cp -r /app/_build/. /build
 ---> Running in 33cfd11e172f
Removing intermediate container 33cfd11e172f
 ---> 805aef08af6e
Successfully built 805aef08af6e
Successfully tagged xibo-linux:latest
demo@demo-Virtual-Machine:~/Downloads/xibo-linux-1.8-r4$ sudo mkdir -p build
demo@demo-Virtual-Machine:~/Downloads/xibo-linux-1.8-r4/build$ sudo docker run -v /home/demo/Downloads/xibo-linux-1.8-r4/build:/build xibo-linux
demo@demo-Virtual-Machine:~/Downloads/xibo-linux-1.8-r4/build$ ls
bin  CMakeCache.txt  CMakeFiles  cmake_install.cmake  CTestTestfile.cmake  generated  install_manifest.txt  Makefile  player
demo@demo-Virtual-Machine:~/Downloads/xibo-linux-1.8-r4/build$ sudo ./player --version
sudo: ./player: command not found
demo@demo-Virtual-Machine:~/Downloads/xibo-linux-1.8-r4/build$ cd bin/
demo@demo-Virtual-Machine:~/Downloads/xibo-linux-1.8-r4/build/bin$ sudo ./player --version
[01:08:07.861] [193453] [error]: [Main] basic_string::_M_construct null not valid
demo@demo-Virtual-Machine:~/Downloads/xibo-linux-1.8-r4/build/bin$ ls
libs  options  player  splash.jpg  tests  ui.glade  watchdog
demo@demo-Virtual-Machine:~/Downloads/xibo-linux-1.8-r4/build/bin$ sudo ./player --version
[sudo] password for demo: 
[14:24:40.416] [193730] [error]: [Main] basic_string::_M_construct null not valid

```

**Comment by dasgarner** [comment]
Are you able to build the latest code in `master` ? I am fairly sure that the way the project builds has changed.

It isn't a bug until our team have been able to verify it, which is why I have labelled it as a question for now. If you're able to submit a PR to fix it, then we'd be very happy to have it! Thanks!

**Comment by dasgarner** [comment]
@Stivius when you get some time please can you check this?

**Comment by serbasii** [comment]
Thanks @dasgarner ,

I tried another pull request #158 under master branch again. I want the way the project is built as in #158 

![image](https://user-images.githubusercontent.com/6322619/87824833-b1a47100-c87e-11ea-911d-cb4ef99a5de2.png)

[ 99%] Building CXX object player/CMakeFiles/player.dir/control/widgets/render/OutputWindowGtk.cpp.o
[100%] Linking CXX executable ../bin/player
[100%] Built target player
[ 24%] Built target common
[ 40%] Built target networking
[ 47%] Built target schedule
[ 85%] Built target player
[ 93%] Built target schedule_tests
[ 95%] Built target options
[ 98%] Built target common_tests
[100%] Built target watchdog
Install the project...
-- Install configuration: "Release"
-- Installing: /app/_build/bin/libs/
**cp: failed to access 'hread_soname_path-NOTFOUND': No such file or directory**
Removing intermediate container dd76073170cc
 ---> 6168f7ff8b32
Step 33/33 : ENTRYPOINT cp -r /app/_build/. /build
 ---> Running in d3185d0688d7
Removing intermediate container d3185d0688d7
 ---> 9975e4b0e877
Successfully built 9975e4b0e877
Successfully tagged xibo-linux-test:latest

**demo@demo-Virtual-Machine:~/Desktop/apps/xibo-linux/build/bin$ sudo ./player --version
[22:50:06.153] [149624] [error]: [Main] basic_string::_M_construct null not valid**

**Comment by dasgarner** [comment]
We changed the way the project was built for good reasons, I do not know why, my colleague will have to answer that for you. 

We will work on our `readme` so that it is clearer how to build the current `develop` and `master` branches. We do not have the resources to make sure older builds still work unfortunately.

**Comment by Stivius** [comment]
@serbasii we've updated `readme` so I suggest you to take a look at the latest `master` with new instructions. Old versions (1.8-R4 and lower) are quite to tricky to build because the build process was changing from one version to another.
