### ISSUE TITLE
Display always gets added as "Display" even if a displayName exists in the settings profile

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo-linux#229]
**Describe the bug**
A new player is being provisioned and a `playerSettings.xml` file is written containing a `displayName`. The Player starts for the first time, and uses "Display" instead of the value from player settings.

**Expected behaviour**
The new Display should be registered with the Display Name provided in Player Settings.

**Comment by Stivius** [comment]
Related to #151
