### ISSUE TITLE
Cannot connect to a v3 CMS

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo-linux#243]
It is not possible to connect to a v3 CMS instance. The options screen doesn't show any error/message when clicking on "Save". And if you start the Player it shows an error line from SOAP, but no message. The last accessed date doesn't update in the CMS.

Expected Behaviour:
The Player should connect and play what it can (the XLF schema is the same).

**Comment by dasgarner** [comment]
After some investigation I think this might be related to headers. If you look at the headers a Linux Player sends with each XMDS request, you will note that some key headers are missing. This is an example request:

````
{"Host":"localhost:80","Content-Length":"1069"}
```

This is a similar request from postman:

```
{"Content-Type":"text\/xml","User-Agent":"PostmanRuntime\/7.26.8","Accept":"*\/*","Host":"localhost","Accept-Encoding":"gzip, deflate, br","Connection":"keep-alive","Content-Length":"893"}
```

Specifically the Content-Type header is missing, but it would be very much desirable to have a User-Agent too for logging purposes.

**Comment by dasgarner** [comment]
There seems to be a further problem here, this time with AppImage.

I've got a snap install and an AppImage install on the same PC, both configured to the same CMS with the same displayId/hardware key.

In options, if I save in the snap it works.
If I save in the appimage it says "500 Internal Server Error".

This is because the `clientCode` field must be an `integer` and AppImage provides a string.

**Comment by Tony-Jab** [comment]
Hi,
I have the same issue after i upgrade my cms to V3.
I have build my own snap (because i don't want automatic update snap) and i get 500 internal error.
With AppImage i have the same issue.
But If i install by snap repository, i didn't get the error.
There is not the last update for the linux-player on git?
Thanks

**Comment by dasgarner** [comment]
Have you tried installing via the `edge` channel in snap? There are certainly things in edge which are not yet promoted to stable channel.

**Comment by Pietzu** [comment]
I have the same problem with CMS V3.

I have tried to build a client by myself from this repository.  I'm also getting "500 internal server error". I tried to build this repository last commit and releases: "edge-00125e7", "edge-0af4e78", "edge-1f0e919", "edge-a7d744f" and "1.8 R6".

I tested the installation from snap edge channel. It works.

**Comment by Tony-Jab** [comment]
Hi, sry for my delay.
Like @Pietzu  i have build client by myself and i have error 500 or another error.
With snap edge channel it works but i can't use it in production. (because snap are updated automatically and i don't want that)

**Comment by Pietzu** [comment]
Is there an update for this?
