### ISSUE TITLE
Project Status - future plans

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo-linux#249]
EDIT: updated status and plans
https://community.xibo.org.uk/t/linux-player-status-and-plans/29612

~The talented developer who created this player for Xibo has moved on to new projects and has very little time to dedicate to this endeavour. Unfortunately Xibo Signage does not have the in-house expertise to continue development and as such development stopped in May 2021. Some small items have been worked on since then, but nothing we have been able to release.~

~Edit: this has been done.
One of the more complex aspects of this project is packaging, and we've tried to incorporate both Snap and AppImage. The main reason for supporting two options here is that we encountered a problem with Snap that we couldn't solve (but that has been solved since by a snapcraft update). Simplifying the build process by only supporting snap would be a great first step to getting us back on track.~

**Comment by Vatorinator** [comment]
i built xibo-linux with docker some months ago locally with a newer "OEM Set" so i guess i can support. should we discuss this a little bit in more detail?
i see 2 things which (from myPointOfView) to be done
a) remove appimage
b) change the OEM set to the "newest" possible set 
to decouple this "organisatorical stuff" from the "coding stuff" i suggst to make a new branch (from master or develop ???) named xibo_linux_OEM_2022 (or something like this)

what do you think ???

**Comment by dasgarner** [comment]
Any help would be greatly appreciated!

Someone has come forward and is working on #252 which is a great start, however they replicating what we have as a first step (existing OEM set). Removing AppImage and updating to a newer OEM set would be fantastic and can be done concurrently with 252 if you have time.

To keep things simple, you could fork the repository and have two branches `feature/remove_appimage` and `feature/update_basedeps`. Each one would be a PR into `develop` once you were happy with it.

The reason I suggest two, is that we can remove app image using the old OEM set and do an immediate build/release into Snap. Then we update OEM set and take a longer testing period to confirm.

Does that sound good?

Thank you again for your offer of help.

**Comment by dasgarner** [comment]
We've made some good progress towards our goals here. The snap build process is fixed and AppImage have been removed. I think we are close to having a 1.8 R7 release.

Help is certainly still wanted and hopefully now that we have a working VSCode build it will become easier to contribute to the project.

As of today we have the following things to work on.
 - [Issue triage](https://github.com/xibosignage/xibo-linux/projects/2)
 - [1.8 R8 milestone](https://github.com/xibosignage/xibo-linux/projects/1?card_filter_query=milestone%3A%221.8+r8%22)

**Comment by Stivius** [comment]
@dasgarner I have some capacity now, do you need help or the project is going to be suspended?

**Comment by dasgarner** [comment]
Thank you for commenting, it is good to hear from you.

We are in the process of exploring other options for the Linux Player and my initial feeling is that this project will be superseded by those efforts. We will update the community and on here when we have a more concrete idea of what is possible and the direction we choose to pursue.

**Comment by dasgarner** [comment]
We have made an announcement regarding the status of this player and our future plans: https://community.xibo.org.uk/t/linux-player-status-and-plans/29612?u=dan
