### ISSUE TITLE
LocalVideo: URL not being decoded

### ISSUE THREAD

**Issue by gamenfs** [xibosignage/xibo-linux#254]
Hi
I found a partial solution for this problem:
https://community.xibo.org.uk/t/rtsp-link-dont-work-on-xibo-linux-player/26304
When I start stream from IP camera on CMS and put layout to client, I get the following error:
[14:46:51.519] [5060] [error]: [LayoutParser - RegionParser - MediaParser - URI] Layout 36 is invalid or missing. Reason: Parse error: rtsp://login:password%40ip/Streaming/Channels/101
The problem is that the client cannot correctly recognize the @ symbol
If I change %40 to @ in the client's uri .xlf file - stream get start.
What module encodes the uri? How is it possible to add this character to the exception?

- CMS: 3.0.7
- Linux Disto: Ubuntu 21.04
- Linux Desktop Environment: GNOME X11
- How the player was launched: snap
- Player Version: 1.8-R6

**Comment by gamenfs** [comment]
> Привет , я нашел частичное решение этой проблемы: https://community.xibo.org.uk/t/rtsp-link-dont-work-on-xibo-linux-player/26304 Когда я запускаю поток с IP-камеры на CMS и передаю макет клиенту, получаю следующую ошибку: [14:46:51.519] [5060] [ошибка]: [LayoutParser - RegionParser - MediaParser - URI] Макет 36 недействителен или отсутствует. Причина: Ошибка синтаксического анализа: rtsp://login:password%40ip/Streaming/Channels/101 Проблема в том, что клиент не может правильно распознать символ @. Если я изменю %40 на @ в клиентском uri .xlf-файле - поток запустится . Какой модуль кодирует uri? Как можно добавить этого персонажа в исключение?
> 
> * Система управления контентом: 3.0.7
> * дистрибутив Linux: Ubuntu 21.04
> * Среда рабочего стола Linux: GNOME X11
> * Как запускался плеер: snap
> * Версия игрока: 1.8-R6

I found a method to start an rtsp stream. Since the problem is in decoding the uri, I changed the method of writing to an xls file without encryption.
To do this, you need to on the server in the file /srv/xibo-cms/lib/Widget/LocalVideo.php change the line:$this->setOption('uri', urlencode($sanitizedParams->getString('uri'))); to $this->setOption('uri', $sanitizedParams->getString('uri'));
I hope this helps someone

**Comment by dasgarner** [comment]
Thanks for reporting this issue - your workaround might break the XLF file generation or transfer to the player, so the correct fix is for the Linux player to url decode the data it finds in the XLF.

I'll log this up as a bug to be fixed when we can.

Thanks

**Comment by gamenfs** [comment]
> Привет,
> 
> У меня точно такая же проблема. Я применил исправление в LocalVideo.php, и URL-адрес в файле xlf перешел.
> 
> Но плеер по-прежнему не хочет воспроизводить поток [ошибка]: [LayoutParser - RegionParser - MediaParser] Макет 20 недействителен или отсутствует. Причина: карта::at
> 
> Мой URL-адрес немного сложнее, и мне нужно было написать и исправить в cms, например `&amp;`, поэтому я не знаю, есть ли у игрока проблемы с другими персонажами:
> 
> `rtsp://Xibo:Xibo*pass@cctv.host.be:554/cam/realmonitor?channel=1&amp;subtype=0`
> 
> * Система управления контентом: 3.1.1
> * дистрибутив Linux: Ubuntu 22.04
> * Среда рабочего стола Linux: GNOME X11
> * Как запускался плеер: snap
> * Версия игрока: 1.8-R6

Hi. I refused to change the configuration of xibo and now use rtsp-proxy (https://github.com/aler9/rtsp-simple-server/tree/98c6cd4650c2efc80fae7e7727d3465190fffc3a) as a temporary solution. Until this problem is solved, this is a good solution.

**Comment by bradyj04** [comment]
is there any updates on this? im encountering the same issue when including usernames and passwords for the RTSP streams
