### ISSUE TITLE
Player cant play a Mpeg-TS stream

### ISSUE THREAD

**Issue by srekkas** [xibosignage/xibo-linux#75]
Same downloaded video plays on Totem player, but xibo-player throws error.
Ubuntu 18.04 desktop minimal install, installed all gstreamer found.

(player:2359): Gtk-CRITICAL **: 21:47:41.276: gtk_widget_set_size_request: assertion 'width >= -1' failed
[21:47:41.352] [002359] [error]: [MediaPlayer] Your GStreamer installation is missing a plug-in.
[21:47:41.352] [002359] [error]: [MediaPlayer] GStreamer encountered a general stream error.

**Comment by dasgarner** [comment]
We've tested the player with multiple codecs, etc and it can play videos.

Can you send us the video that is failing and we will try it? https://transfer.xibo.org.uk

**Comment by srekkas** [comment]
One is Mpeg-TS stream from TVheadend DVB, others like this
https://transfer.xibo.org.uk/8d726a102552

**Comment by srekkas** [comment]
Hello, player updated to R1. Now uploaded video plays, but Mpeg-TS still throws error.
thank you for great software, cant't wait to ditch windows players, only 5 but still headache :) Waiting for new TV with webos, hope it works on that.

**Comment by dasgarner** [comment]
thanks for the feedback and the example, I've updated the title accordingly.
