### ISSUE TITLE
Linux Player cannot play m3u8 playlist

### ISSUE THREAD

**Issue by myymi** [xibosignage/xibo-linux#83]
Good day! 
The player cannot play m3u8 videostreams, for example this one: https://tv.eenet.ee/hls/konnakotkas.m3u8 

The player is 1.8 and CMS version is 2.0.0. 
Windows players play this and similar streams nicely.

**Comment by dasgarner** [comment]
I still have the same problem :

```
gstreamer|1.0|player|application/x-hls decoder|decoder-application/x-hls
This URI cannot be played
[MediaPlayer] Your GStreamer installation is missing a plug-in.
[MediaPlayer] Debug details: gstdecodebin2.c(4565): gst_decode_bin_expose (): /GstPipeline:pipeline/GstDecodeBin:decodebin72: no suitable plugins found: Missing decoder: application/x-hls (application/x-hls)
```

**Comment by myymi** [comment]
true, this link was nest camera for eagle. Chicks are already hatched by now and flown off, so the camera and stream were taken down. You might try this: http://tv.eenet.ee/hls/linnulaul.m3u8
