### ISSUE TITLE
Player does not download files other that .html

### ISSUE THREAD

**Issue by guile2912** [xibosignage/xibo-linux#90]
I am using Xibo CMS 2.0.3, Linux player 1.8 - code version 108, and the last windows player.
Everything works fine with the window player, but the Linux player is stuck on the launch image, because it cannot download all the files needed.
It seems like the player can only download .html files, all other file types fails. On the CMS side, I do not have any apache log about failed requests, so it seems like it is the player failing to ask correctly for the files.

Thanks,

Here are my Xibo linux player logs:
[14:34:37.265] [005798] [error]: [23.mp4] Download error: [HTTP] Connection refused

[14:34:37.266] [005801] [error]: [26.png] Download error: [HTTP] Connection refused

[14:34:37.266] [005800] [error]: [29.png] Download error: [HTTP] Connection refused

[14:34:37.270] [005803] [error]: [42.xlf] Download error: [HTTP] Connection refused
[full-client-logs.log](https://github.com/xibosignage/xibo-linux/files/3387704/full-client-logs.log)

And here are my Xibo CMS apache access logs at the same time:
```172.16.254.56 - - [12/Jul/2019:18:34:34 +0000] "POST /xmds.php?v=5 HTTP/1.1" 200 1861 "-" "-"
172.16.254.56 - - [12/Jul/2019:18:34:35 +0000] "POST /xmds.php?v=5 HTTP/1.1" 200 10380 "-" "-"
172.16.254.56 - - [12/Jul/2019:18:34:35 +0000] "POST /xmds.php?v=5 HTTP/1.1" 200 3236 "-" "-"
172.16.254.56 - - [12/Jul/2019:18:34:35 +0000] "POST /xmds.php?v=5 HTTP/1.1" 200 3358 "-" "-"
172.16.254.56 - - [12/Jul/2019:18:34:35 +0000] "POST /xmds.php?v=5 HTTP/1.1" 200 2888 "-" "-"
172.16.254.56 - - [12/Jul/2019:18:34:35 +0000] "POST /xmds.php?v=5 HTTP/1.1" 200 3095 "-" "-"
172.16.254.56 - - [12/Jul/2019:18:34:35 +0000] "POST /xmds.php?v=5 HTTP/1.1" 200 3114 "-" "-"
172.16.254.56 - - [12/Jul/2019:18:34:35 +0000] "POST /xmds.php?v=5 HTTP/1.1" 200 3274 "-" "-"
172.16.254.56 - - [12/Jul/2019:18:34:35 +0000] "POST /xmds.php?v=5 HTTP/1.1" 200 3078 "-" "-"
172.16.254.56 - - [12/Jul/2019:18:34:35 +0000] "POST /xmds.php?v=5 HTTP/1.1" 200 4522 "-" "-"
172.16.254.56 - - [12/Jul/2019:18:34:35 +0000] "POST /xmds.php?v=5 HTTP/1.1" 200 4146 "-" "-"
172.16.254.56 - - [12/Jul/2019:18:34:36 +0000] "POST /xmds.php?v=5 HTTP/1.1" 200 518 "-" "-"
172.16.254.56 - - [12/Jul/2019:18:34:36 +0000] "POST /xmds.php?v=5 HTTP/1.1" 200 3032 "-" "-"
172.16.254.56 - - [12/Jul/2019:18:34:36 +0000] "POST /xmds.php?v=5 HTTP/1.1" 200 2896 "-" "-"
172.16.254.56 - - [12/Jul/2019:18:34:36 +0000] "POST /xmds.php?v=5 HTTP/1.1" 200 4275 "-" "-"
172.16.254.56 - - [12/Jul/2019:18:34:35 +0000] "POST /xmds.php?v=5 HTTP/1.1" 200 4504 "-" "-"
172.16.254.56 - - [12/Jul/2019:18:34:35 +0000] "POST /xmds.php?v=5 HTTP/1.1" 200 4588 "-" "-"
172.16.254.56 - - [12/Jul/2019:18:34:38 +0000] "POST /xmds.php?v=5 HTTP/1.1" 200 518 "-" "-"
172.16.254.56 - - [12/Jul/2019:18:34:38 +0000] "POST /xmds.php?v=5 HTTP/1.1" 200 508 "-" "-"
172.16.254.56 - - [12/Jul/2019:18:34:39 +0000] "POST /xmds.php?v=5 HTTP/1.1" 200 522 "-" "-"```

**Comment by guile2912** [comment]
I found the problem:
The client does not care if the server is on a custom port ( 8080 for exemple ) and so always request the 
files on port 80 . that explains why requests are refused and do not even hit the CMS server.

**Comment by dasgarner** [comment]
Thank you for your diagnostics - we will take a look at that.

**Comment by Stivius** [comment]
Hello @guile2912. If I'm not mistaken your CMS is located on the 80 port while the server where you store resources for download is on a custom port, right?

**Comment by guile2912** [comment]
Hello,
No, the CMS is on port 8080
I have added debugs to the XmdsRequestSender, and it shows that the request does not take custom ports into account at all, most calls are made without any port specified, so on the 80. 
Also, even is the XmdsRequestSender should be a singloton, I supect it is often instanciated, but I did not had time to properly setup my dev machine yet to be able to do step debugging.

**Comment by Stivius** [comment]
Ok, seems to me I've found the reason. RequiredFiles XMDS response sends URLs without custom port but the player thinks that port should have been provided together with URLs.
@guile2912 thanks for reporting this tricky issue!

**Comment by dasgarner** [comment]
I've run tests against a locally running CMS on port 8081. Here is my postman request to RequiredFiles:

```
curl -X POST \
  'http://localhost:8081/xmds.php?v=5' \
  -H 'Content-Type: text/xml' \
  -H 'cache-control: no-cache' \
  -d '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="urn:xmds" xmlns:types="urn:xmds/encodedTypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <soap:Body soap:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
    <tns:RequiredFiles>
      <serverKey xsi:type="xsd:string">test</serverKey>
      <hardwareKey xsi:type="xsd:string">postman</hardwareKey>
    </tns:RequiredFiles>
  </soap:Body>
</soap:Envelope>'
```

Here is a sample of the response I get (I've stripped the SOAP envelope)

```
<?xml version="1.0"?> <files generated="2019-10-18 08:57:01" fitlerFrom="2019-10-18 08:00:00" fitlerTo="2019-10-20 08:00:00"> <file type="media" id="27" size="95785" md5="3c9137d88a00b1ae0b41ff6a70571615" path="http://localhost:8081/xmds.php?file=15e91f05ac06a9d3d433730ee6bafbfc8b4835f2f891f2bef339e9bd9fe4a348&amp;displayId=9&amp;type=M&amp;itemId=27" saveAs="jquery-1.11.1.min.js" download="http"/> <file type="media" id="396" size="67016" md5="cd287dcbb4564b57692cfed0e2e58345" path="http://localhost:8081/xmds.php?file=15e91f05ac06a9d3d433730ee6bafbfc8b4835f2f891f2bef339e9bd9fe4a348&amp;displayId=9&amp;type=M&amp;itemId=396" saveAs="weathericons-regular-webfont.ttf" download="http"/> <file type="media" id="42" size="1337459" md5="926affd0ae3d3b69e6071b26875638c8" path="http://localhost:8081/xmds.php?file=15e91f05ac06a9d3d433730ee6bafbfc8b4835f2f891f2bef339e9bd9fe4a348&amp;displayId=9&amp;type=M&amp;itemId=42" saveAs="pdf.worker.js" download="http"/>
.....
```

It seems to me that the paths are correct in the response, and have the 8081 port as expected. 

Perhaps this is specific to @guile2912 and @Stivius environments?

**Comment by Stivius** [comment]
Confirmed it's a bug on the player side
